### ISSUE TITLE
Cant build on Ubuntu 14.04 64 bits

### ISSUE THREAD

**Issue by Murii** [taylor001/crown#48]
compilation terminated.
make[2]: *** [../../linux64/obj/x64/development/openal/third/openal/Alc/backends/alsa.o] Error 1
make[1]: *** [openal] Error 2
make[1]: Leaving directory `/home/vlad/crown/.build/projects/linux'
make: *** [linux-development64] Error 2

using make linux-development64 or linux-debug64

**Comment by taylor001** [comment]
Cannot repro here. Can you paste the whole build log?

**Comment by Murii** [comment]
Generating .build/projects/linux/crown.make...
Done.
make -R -C .build/projects/linux config=debug64
make[1]: Entering directory `/home/vlad/crown/.build/projects/linux'
==== Building bgfx (debug64) ====
==== Building shaderc (debug64) ====
==== Building openal (debug64) ====
alsa.c
In file included from ../../../third/openal/OpenAL32/Include/alMain.h:35:0,
                 from ../../../third/openal/Alc/backends/alsa.c:27:
../../../third/openal/include/atomic.h:16:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
make[2]: *** [../../linux64/obj/x64/debug/openal/third/openal/Alc/backends/alsa.o] Error 1
make[1]: *** [openal] Error 2
make[1]: Leaving directory `/home/vlad/crown/.build/projects/linux'
make: *** [linux-debug64] Error 2

**Comment by taylor001** [comment]
This should fix that: https://github.com/taylor001/crown/commit/5b487ed8c7cb708c77e69d95a1a223328af9e5d1

**Comment by Murii** [comment]
Will see!

**Comment by Murii** [comment]
New error :
 Linking openal
==== Building crown (debug64) ====
Creating ../../linux64/obj/x64/debug/crown
console_server.cpp
device.cpp
In file included from ../../../engine/physics/physics_world.h:11:0,
                 from ../../../engine/world/world.h:12,
                 from ../../../engine/device.cpp:16:
../../../engine/physics/physics_callback.h:10:21: fatal error: PxActor.h: No such file or directory
 #include "PxActor.h"
                     ^
compilation terminated.
make[2]: *** [../../linux64/obj/x64/debug/crown/engine/device.o] Error 1
make[1]: *** [crown] Error 2
make[1]: Leaving directory `/home/vlad/crown/.build/projects/linux'
make: *** [linux-debug64] Error 2

**Comment by taylor001** [comment]
You probably have to set PHYSX_SDK_LINUX environment variable.

**Comment by Murii** [comment]
how? :)

**Comment by taylor001** [comment]
Just extract PhysX SDK somewhere and https://github.com/taylor001/crown#prerequisites-for-linux

**Comment by Murii** [comment]
Okay!

**Comment by Murii** [comment]
PhysX 3.3.2?

**Comment by taylor001** [comment]
Yep, should be fine.
